# this file will be moved to the root so all of the path are relative to the root
version: "3"
services:
  web-ui:
    image: node:10
    build: ./web-ui
    volumes:
      - ./web-ui:/app/front
    working_dir: /app/front
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
    command: yarn start:dev
  api-endpoint:
    image: node:10
    build: ./api-endpoint
    volumes:
      - ./api-endpoint:/app/endpoint
    working_dir: /app/endpoint
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: yarn start:dev
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

